Win_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script: 
        - git lfs env
        - git lfs install
        - git submodule init
        - git submodule update
        - rmdir stage /s /q
        - rmdir build /s /q
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON -DHUNTER_ROOT="C:\.hunter" -DENABLE_LOG=ON
        - cmake --build . --target install
        - ..\stage\bin\summit-app-grid.exe --help
        - mkdir ..\test\secure
        - cd ..
        - time /t
        - stage\bin\summit-app-grid.exe -n 3 -d 4 -i lib\Summit.Grid-CI-data\banff\25_20171218123658 -o test\secure\banff\25_20171218123658 -a lib\Summit.Grid-CI-data -e test\secure -m -r cen_file,tsv_probe_list,mat_tiff
        - time /t
        - stage\bin\summit-app-grid.exe -n 5 -d 4 -i lib\Summit.Grid-CI-data\yz01\877-09_without96 -o test\secure\yz01\877-09_without96 -a lib\Summit.Grid-CI-data -e test\secure -m -r cen_file,tsv_probe_list,mat_tiff
        - time /t
        - stage\bin\summit-app-grid.exe -n 4 -d 4 -i lib\Summit.Grid-CI-data\yz01-41\185_20200520130056 -o test\secure\yz01-41\185_20200520130056 -a lib\Summit.Grid-CI-data -e test\secure -m -r cen_file,tsv_probe_list,mat_tiff
        - time /t
        - stage\bin\summit-app-grid.exe -n 3 -d 4 -i lib\Summit.Grid-CI-data\lassen\60_C20200528134935 -o test\secure\lassen\60_C20200528134935 -a lib\Summit.Grid-CI-data -e test\secure -m -r cen_file,tsv_probe_list,mat_tiff
        - time /t
        - stage\bin\summit-app-light_mean.exe -i lib\Summit.Grid-CI-data\yz01\877-09_without96\grid\channels\CY3_750ms\heatmap.csv -o light_mean_AM1E.csv -c yz01 -m AM1E -e light_mean_AM1E_probes.csv
        - time /t
    only:
        - 1.0.x
        - 1.1.x
        - 1.2.x
        - 1.3.x
    tags:
        - WIN

CentOS_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script: 
        - git submodule init
        - git submodule update
        - source /opt/rh/devtoolset-7/enable
        - source /opt/rh/python27/enable
        - source /opt/rh/rh-python35/enable
        - rm -rf stage
        - rm -rf build
        - mkdir -p build
        - cd build
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON -DENABLE_LOG=ON
        - cmake --build . --target install
        - ../stage/bin/summit-app-grid --help
        - mkdir -p ../test/secure
        - cd ..
        - ./stage/bin/summit-app-grid -n 3 -d 4 -i lib/Summit.Grid-CI-data/banff/25_20171218123658 -o test/secure/banff/25_20171218123658 -a lib/Summit.Grid-CI-data -e test/secure -m -r cen_file,tsv_probe_list,mat_tiff
        - ./stage/bin/summit-app-grid -n 5 -d 4 -i lib/Summit.Grid-CI-data/yz01/877-09_without96 -o test/secure/yz01/877-09_without96 -a lib/Summit.Grid-CI-data -e test/secure -m -r cen_file,tsv_probe_list,mat_tiff
        - ./stage/bin/summit-app-grid -n 4 -d 4 -i lib/Summit.Grid-CI-data/yz01-41/185_20200520130056 -o test/secure/yz01-41/185_20200520130056 -a lib/Summit.Grid-CI-data -e test/secure -m -r cen_file,tsv_probe_list,mat_tiff
        - ./stage/bin/summit-app-grid -n 3 -d 4 -i lib/Summit.Grid-CI-data/lassen/60_C20200528134935 -o test/secure/lassen/60_C20200528134935 -a lib/Summit.Grid-CI-data -e test/secure -m -r cen_file,tsv_probe_list,mat_tiff
        - ./stage/bin/summit-app-light_mean -i lib/Summit.Grid-CI-data/yz01/877-09_without96/grid/channels/CY3_750ms/heatmap.csv -o light_mean_AM1E.csv -c yz01 -m AM1E -e light_mean_AM1E_probes.csv
    only:
        - 1.0.x
        - 1.1.x
        - 1.2.x
        - 1.3.x
    tags:
        - CENTOS

Package_CI:
    variables:
      PERSONAL_ACCESS_TOKEN: "7xEjQsPgsGdJxyAzBetd"
    stage: build
    before_script:
        - echo %USERPROFILE%
        - echo %CI_PROJECT_DIR%
        - echo %PERSONAL_ACCESS_TOKEN%
    script: 
        - rmdir stage /s /q
        - rmdir build /s /q
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" .. -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DINSTALL_DEPS=ON -DBUILD_TESTS=OFF -DENABLE_LOG=ON -DENABLE_CPACK=ON -DHUNTER_ROOT="C:\.hunter"
        - cmake --build . --target install -- -j 6
        - cpack
        - ..\stage\bin\summit-app-grid.exe --version
        - python -m venv testing
        - testing\Scripts\pip install requests
        - testing\Scripts\python ..\bundle.py %PERSONAL_ACCESS_TOKEN%
    only:
        - web
    tags:
        - WIN
