Win_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script: 
        - rmdir stage /s /q
        - rmdir build /s /q
        - mkdir build
        - cd build
        - cmake -G "MinGW Makefiles" ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON
        - cmake --build . --target install
    only:
        - master
    tags:
        - WIN

CentOS_CI:
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    stage: build
    script: 
        - source /opt/rh/devtoolset-7/enable
        - source /opt/rh/python27/enable
        - source /opt/rh/rh-python35/enable
        - rm -rf stage
        - rm -rf build
        - mkdir -p build
        - cd build
        - cmake ../ -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX=../stage -DBUILD_TESTS=ON -DINSTALL_DEPS=ON
        - cmake --build . --target install
    only:
        - master
    tags:
        - CENTOS
